version: '3.8'

networks: 
  app-tier:
    driver: bridge
services: 
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pis_review_db
      - 
    ports:
      - '3307:3306'
    expose:
      - 3307
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-mysql-app
    depends_on:
      - mysql
    command: ["mysql:3307"]

volumes: 
  db-config:
  db-data: